blank_issues_enabled: false

contact_links:
  - name: Questions & Discussions
    url: https://github.com/kenso312/nestjs-v9-webpack-boilerplate/discussions
    about: Use GitHub discussions for message-board style questions and discussions.
